user nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        # Statische Dateien IMMER vor dem SPA-Fallback behandeln
        location ~* \.(svg|png|jpg|jpeg|gif|ico|css|js|woff2?)$ {
            try_files $uri =404;
        }

        # API Proxy
        location /api/ {
            proxy_pass <YOUR-ADDRESS-HERE>;
            proxy_set_header Host <YOUR-ADDRESS-HERE>;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header X-Debug-Proxy-Pass $request_uri;
        }

        # SPA (React) Fallback
        location / {
            try_files $uri /index.html;
        }
    }
}
