import { FormState } from "../types/types";
import {
  isValidIRI,
  notEmptyValidator,
} from "../utils/validator";

const COURSE_COMPETENCE_FRAMEWORK = "GRETA";
const METADATA_FRAMEWORK = "moochub";

const initialFormState: FormState = {
  suitableQ1: {
    value: "",
    id: "suitableQ1",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  suitableQ2: {
    value: "",
    id: "suitableQ2",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  suitableQ3: {
    value: "",
    id: "suitableQ3",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  courseTitle: {
    value: "",
    id: "courseTitle",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  courseDescription: {
    value: "",
    id: "courseDescription",
    validator: null,
    required: false,
    error: false,
  },
  courseUrl: {
    value: "",
    id: "courseUrl",
    validator: (value: string) => notEmptyValidator(value) && isValidIRI(value),
    required: true,
    error: false,
  },
  courseStart: {
    value: null,
    id: "courseStart",
    validator: null,
    required: false,
    error: false,
  },
  courseEnd: {
    value: null,
    id: "courseEnd",
    validator: null,
    required: false,
    error: false,
  },
  courseExpires: {
    value: null,
    id: "courseExpires",
    validator: null,
    required: false,
    error: false,
  },
  courseType: {
    value: "",
    id: "courseType",
    validator: null,
    required: false,
    error: false,
  },
  courseAsynchronous: {
    value: "",
    id: "courseAsynchronous",
    validator: null,
    required: false,
    error: false,
  },
  locationName: {
    value: "",
    id: "locationName",
    validator: null,
    required: false,
    error: false,
  },
  locationStreetNumber: {
    value: "",
    id: "locationStreetNumber",
    validator: null,
    required: false,
    error: false,
  },
  locationZip: {
    value: "",
    id: "locationZip",
    validator: null,
    required: false,
    error: false,
  },
  locationCity: {
    value: "",
    id: "locationCity",
    validator: null,
    required: false,
    error: false,
  },
  courseCompetenceFramework: {
    value: COURSE_COMPETENCE_FRAMEWORK,
    id: "courseCompetenceFramework",
    validator: null,
    required: true,
    error: false,
  },
  courseSkills: {
    value: [],
    id: "courseSkills",
    validator: null,
    required: false,
    error: false,
  },
  metadataFramework: {
    value: METADATA_FRAMEWORK,
    id: "metadataFramework",
    validator: null,
    required: true,
    error: false,
  },
  publisherName: {
    value: "",
    id: "publisherName",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  publisherType: {
    value: "",
    id: "publisherType",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  creatorName: {
    value: "",
    id: "creatorName",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  creatorType: {
    value: "",
    id: "creatorType",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  licenseIdentifier: {
    value: "",
    id: "licenseIdentifier",
    validator: notEmptyValidator,
    required: true,
    error: false,
  },
  inLanguage: {
    value: ["de"],
    id: "inLanguage",
    validator: null,
    required: false,
    error: false,
  },
  durationUnit: {
    value: "h",
    id: "durationUnit",
    validator: null,
    required: false,
    error: false,
  },
  durationValue: {
    value: "",
    id: "durationValue",
    validator: null,
    required: false,
    error: false,
  },
  keywords: {
    value: "",
    id: "keywords",
    validator: null,
    required: false,
    error: false,
  },
  access: {
    value: [],
    id: "access",
    validator: null,
    required: false,
    error: false,
  },
};

export { initialFormState };
